### ISSUE TITLE
fit_mle testing too long

### ISSUE THREAD

**Issue by jojal5** [JuliaExtremes/PMP.jl#2]
Locally, the test for the fit_mle applied on the type PearsonType1 is fast. But when running it with the test command in the package manager, it is incredibly slow. I do not understand why.

The fit_mle test in the "test/distributions/pearsontype1.jl" file should be uncommented when the problem is resolved.

**Comment by houton199** [comment]
@jojal5 dans le test qui échoue (https://github.com/JuliaExtremes/PMP.jl/pull/1/checks?check_run_id=13583355376), il semble y avoir une erreur avec `LocationScale`, as-tu ça aussi localement?

**Comment by jojal5** [comment]
@houton199  C'est un warning. Le test échoue parce que le délai de calcul est expiré. En local, j'ai le même warning et c'est interminable avant que les tests se complètent avec la commande test dans le gestionnaire de paquets.
