### ISSUE TITLE
check_args de PearsonType1

### ISSUE THREAD

**Issue by anneanas** [JuliaExtremes/PMP.jl#4]
On a un problème avec la fonction qui crée la structure PearsonType1, les arguments de check_args ne fonctionnent pas. J'obtiens le message d'erreur suivant lorsque je charge la librairie :

```
│    LoadError: MethodError: no method matching var"@check_args"(::LineNumberNode, ::Module, ::Symbol, ::Expr, ::Expr, ::Expr)
│    Closest candidates are:
│      var"@check_args"(::LineNumberNode, ::Module, ::Any, ::Any) at ~/.julia/packages/Distributions/RAeyY/src/utils.jl:3
│    in expression starting at /Users/anne/Desktop/uni/maitrise/PMP.jl/src/distributions/pearsontype1.jl:38
```

En ce moment, la fonction est écrite de la manière suivante : 

`@check_args PearsonType1 ((a,b), b>a) (α, α > zero(α)) (β, β > zero(β))`

J'ai essayé de jouer avec les arguments et parenthèses mais ça n'a pas fonctionné.

**Comment by houton199** [comment]
Essaie de mettre à jour tes librairies.

**Comment by anneanas** [comment]
C'était ça en effet, merci :) !!!
